### ISSUE TITLE
chefspec redis_exporter

### ISSUE THREAD

**Issue by bliuchak** [evilmartians/chef-prometheus-exporters#11]
Hello,

I'd like to test `redis_exporter` resource in my cookbook using chefspec. But I've encountered with a problem that I can't find action matcher for it.

```rb
it 'install prometheus redis exporter' do
  expect(chef_run).to install_redis_exporter('main')
end
```

With code above I've got next error
```bash
Failures:

  1) xxxxx_redis::default When all attributes are default, on centos-7.3.1611 install prometheus redis exporter
     Failure/Error: expect(chef_run).to install_redis_exporter('main')

     NoMethodError:
       undefined method `install_redis_exporter' for #<RSpec::ExampleGroups::xxxxxRedisDefault::WhenAllAttributesAreDefaultOnCentos731611:0x007fb0abce0c08>
       Did you mean?  install_windows_feature
     # ./spec/unit/recipes/default_spec.rb:77:in `block (3 levels) in <top (required)>'
```

Could someone please point me what I'm doing wrong?

I'm using:
- cookbook `depends 'prometheus_exporters', '~> 0.6.1'`
- Chef Development Kit Version: 1.4.3
- chef-client version: 13.5.3
- delivery version: master (41b94ffb5efd33723cf72a89bf4d273c8151c9dc)
- berks version: 6.3.1
- kitchen version: 1.16.0
- inspec version: 1.25.1

**Comment by dragonsmith** [comment]
@bliuchak hello!

Sorry for such a long response.

In fact, I was ignoring ChefSpec for quite a long time in favor of InSpec, so I may have a limited context, but I think you running your test not in a proper way or something.

I've peeked into [examples](https://github.com/chefspec/chefspec/tree/master/examples/) and it turns out the current ChefSpec autogenerates matchers.

Here is my implementation of the tests: https://github.com/evilmartians/chef-prometheus-exporters/blob/master/test/cookbooks/testrig/spec/chefspec.rb

I've bumped into two things during my short research:
1. I had to invoke `ChefSpec::Runner` to get matcher methods.
2. `rspec` should be [invoked from the root directory](https://github.com/evilmartians/chef-prometheus-exporters/blob/master/.travis.yml) for Berkshelf to resolve correctly.

I hope that helps! Thank you for using my cookbook and providing a feedback!
